---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - oTel-collector.yaml
  - otel.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - loki-monitoring.yaml
#  - tempo.yaml
